version: '3'

tasks:

  dev:
    deps:
      - site.dev
      - storybook.dev

  prod:
    deps:
      - site.prod
      - storybook.prod

  test: >-
    npx jest
    --config ./jest.config.js
    --passWithNoTests

  lint: >-
    npx eslint
    ./src
    --ext .ts
    --cache

  site.dev:
    deps:
      - site.clean
    cmds:
      - >-
        npx gatsby develop
        --host 0.0.0.0
        --port 8000

  site.clean:
    - npx rimraf ./.cache
    - npx rimraf ./public

  site.prod:
    - npx gatsby build
    - mv ./public/* ./dist${FRONTEND__SITE__PATH}

  storybook.dev: >-
    npx start-storybook
    -p 9001
    --ci
    -c ./tools/storybook

  storybook.serve: >-
    npx serve dist
    -p 9001
    -s
    -c ./tools/storybook

  storybook.prod: >-
    npx build-storybook
    --config-dir ./tools/storybook
    --output-dir ./dist${FRONTEND__SITE__PATH}/storybook
