version: '3'

tasks:

  dev:
    deps:
      - site.dev
      - storybook.dev

  prod:
    cmds:
      - task: site.prod
      - task: storybook.prod

  serve:
    cmds:
      - task: site.serve

  test: >-
    npx jest
    --config ./jest.config.js
    --passWithNoTests

  lint: >-
    npx eslint
    ./src
    --ext .ts
    --cache

  site.clean:
    - npx rimraf ./dist/**/*
    - npx rimraf ./.cache/**/*
    - npx rimraf ./public/**/*

  site.dev:
    deps:
      - site.clean
    env:
      FRONTEND__SITE__DOMAIN: '{{ default "localhost" .SITE_DOMAIN}}'
      FRONTEND__SITE__ROOT: '{{ default "" .SITE_ROOT}}'
      FRONTEND__SITE__PATH: '{{ default "" .SITE_PATH}}'
    cmds:
      - >-
        npx gatsby develop
        --host $HOST
        --port $PORT

  site.prod:
    deps:
      - site.clean
    description: |
      Create a production build of the site.

      Takes in two parameters (that have defaults) to control
      how links within the site are generated.

      - uses `<SITE_ROOT><SITE_PATH>` to prefix all the links generated
      - uses `https://<SITE_DOMAIN>` to configure siteMetaData
      - builds into `./public`
      - then gets moved to `./dist/<SITE_PATH>/`
    env:
      FRONTEND__SITE__DOMAIN: "{{.SITE_DOMAIN}}"
      FRONTEND__SITE__ROOT: "{{.SITE_ROOT}}"
      FRONTEND__SITE__PATH: "{{.SITE_PATH}}"
    cmds:
      - >-
        npx gatsby build
        --prefix-paths
      - whoami
      - ls -al ./dist
      - >-
        npx cpy-cli
        '**/*'
        '../dist/{{.SITE_PATH}}'
        --cwd=./public
        --parents

  site.serve:
    env:
      FRONTEND__SITE__DOMAIN: "{{.SITE_DOMAIN}}"
      FRONTEND__SITE__ROOT: "{{.SITE_ROOT}}"
      FRONTEND__SITE__PATH: "{{.SITE_PATH}}"
    cmds:
      - >-
        npx gatsby serve
        --prefix-paths
        --host $HOST
        --port $PORT

  env.dump:
    env:
      FRONTEND__SITE__DOMAIN: "{{.SITE_DOMAIN}}"
      FRONTEND__SITE__ROOT: "{{.SITE_ROOT}}"
      FRONTEND__SITE__PATH: "{{.SITE_PATH}}"
    cmds:
      - env

  storybook.dev: >-
    npx start-storybook
    -p 9001
    --ci
    --config-dir ./tools/storybook

  storybook.prod: >-
    npx build-storybook
    --config-dir ./tools/storybook
    --output-dir ./dist/{{.SITE_PATH}}/storybook
