builds:
  docker-make:
    context: /
    dockerfile: Dockerfile
    pushes:
      - 'on_branch:master=airtonix/zenobius:latest'
      - 'on_tag=airtonix/zenobius:{git_tag}'
      - 'always=airtonix/zenobius:{scommitid}'
    labels:
      - 'com.project.git.commitid={fcommitid}'
      - 'com.project.git.branch={git_branch}'
      - 'com.project.git.date={date}'
    dockerignore:
      - .git
      - .vscode
      - .circleci
      - node_modules