version: "2.0"

services:

  site:
    image: docker.pkg.github.com/airtonix/zenobi.us:develop
    ports:
      - 8000:8000
    environment:
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - DEBUG=project*,config*
      - GATSBY_WEBPACK_PUBLICPATH=/
    volumes:
      - "./src:/app/src"
      - "./dist:/app/dist"
      - "./config:/app/config"
      - "./package.json:/app/package.json"
