version: "2.3"

services:

  frontend:
    image: docker.pkg.github.com/airtonix/zenobi.us/frontend:6fd48c2
    environment:
      # These variables can be overriden
      # by either the .env file or settings them as envs
      # on the host where you run docker-compose
      - DUMP
      - FRONTEND__SITE__PATH
      - FRONTEND__SITE__ROOT
      - FRONTEND__SITE__DOMAIN
      - FRONTEND__USER_ID
      - FRONTEND__USER_NAME
