version: "2.0"

services:

  frontend:
    image: docker.pkg.github.com/airtonix/zenobi.us/frontend:5776c08
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - DEBUG=project*,config*
    volumes:
      - ./frontend:/app
      - /app/node_modules/
