version: "2.3"

services:

  frontend:
    image: docker.pkg.github.com/airtonix/zenobi.us/frontend:c8b5f61
    environment:
      # These variables can be overriden
      # by either the .env file or settings them as envs
      # on the host where you run docker-compose
      - DUMP
      - FRONTEND__SITE__PATH
      - FRONTEND__SITE__ROOT
      - FRONTEND__SITE__DOMAIN
