version: "2.0"

services:

  tool:
    image: airtonix/${npm_package_docker_image}:${npm_package_docker_tag}
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DEBUG=config*
    volumes:
      - "./src:/app/src"
      - "./dist:/app/dist"
      - "./config:/app/config"
      - "./package.json:/app/package.json"
      - "./.babelrc:/app/.babelrc"
      - "./node_modules/@compositor/x0:/app/node_modules/@compositor/x0"
