version: "2.0"

services:

  tool:
    image: airtonix/${npm_package_name}:${npm_package_version}
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DEBUG=config*
    volumes:
      - "./src:/app/src"
      - "./config:/app/config"
      - "./package.json:/app/package.json"
