version: "2.0"

services:

  frontend:
    image: docker.pkg.github.com/airtonix/zenobi.us/frontend:42d2e5f
    ports:
      - 3000:3000
      - 9001:9001
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
      - DEBUG=project*,config*
    volumes:
      - ./frontend:/app
      - /app/node_modules/
    command: task dev
