version: "2.0"

services:

  tool:
    image: ${npm_package_docker_image}:${npm_package_docker_tag}
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - DEBUG=config*
    volumes:
      - "./src:/app/src"
      - "./dist:/app/dist"
      - "./config:/app/config"
      - "./package.json:/app/package.json"
      - "./.babelrc:/app/.babelrc"
