version: "2.0"

services:

  tool:
    image: airtonix/${npm_package_name}:${npm_package_version}
    ports:
      - 3000:3000
    volumes:
      - "./src:/app/src"
      - "./package.json:/app/package.json"