version: "2.0"

services:

  tool:
    image: airtonix/${npm_package_name}:${npm_package_version}
    ports:
      - 3000:3000
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - DEBUG=config*
    volumes:
      - "./src:/app/src"
      - "./config:/app/config"
      - "./package.json:/app/package.json"
