version: "2.0"

services:

  tool:
    image: ${npm_package_docker_image}:${npm_package_docker_tag}
    ports:
      - 8000:8000
    environment:
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - DEBUG=project*,config*
      - GATSBY_WEBPACK_PUBLICPATH=/
    volumes:
      - "./src:/app/src"
      - "./dist:/app/dist"
      - "./config:/app/config"
      - "./package.json:/app/package.json"
