# code: language=yaml
version: '3'

vars:
  GIT_REPO: ssh://git@github.com/airtonix/zenobi.us.git
  DOCKER_REGISTRY: docker.pkg.github.com/airtonix/zenobi.us
  SERVICE: frontend
  STAGE: local
  VERSION:
    sh: git rev-parse --short HEAD

includes:
  docker: ./tools/tasks/docker.yml

tasks:

  default:
    - task: setup

  setup:
    - task: create

  create:
    - task: docker:build
      vars:
        SERVICE: frontend
        TAG: '{{.VERSION}}'
    - task: docker:templates

  dev:
    - task: docker:up

  frontend.build:
    - task: docker:run
      vars:
        SERVICE: frontend
        COMMAND: task prod

  frontend.shell:
    cmds:
      - task: docker:run
        vars:
          SERVICE: frontend
          COMMAND: /bin/sh

  frontend.deploy:
    env:
      NODE_DEBUG: gh-pages
    cmds:
      - ls -al frontend/dist/{{.}}
      - touch package.json
      - >-
        npx gh-pages
        --add
        --dist=frontend/dist/{{.}}
        --repo={{.GIT_REPO}}
      - npx rimraf package.json

  frontend.test:
    cmds:
      - task: docker:run
        vars:
          SERVICE: frontend
          COMMAND: task test

  frontend.lint:
    cmds:
      - task: docker:run
        vars:
          SERVICE: frontend
          COMMAND: task lint
