
<!-- logos -->
    <section class="logos">
      <div class="container">
        <div><img src="img/logos/mashable.png" alt=""></div>
        <div><img src="img/logos/guardian.png" alt=""></div>
        <div><img src="img/logos/forbes.png" alt=""></div>
        <div><img src="img/logos/red-bull.png" alt=""></div>
        <div><img src="img/logos/ny-times.png" alt=""></div>
      </div>
    </section>
    