version: "2"
jobs:

  build_image:
    working_directory: /build
    docker: {image: "docker:17.05.0-ce-git" }
    steps:
      - checkout
      - setup_remote_docker

      - restore_cache:
          keys:
            - image-{{ .Branch }}
          paths:
            - /caches/docker-image.tar

      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/docker-image.tar | true

      - run:
          name: Build application Docker image
          when: on_success
          command: |
            docker login --username=${DOCKER_USERNAME} --password=${DOCKER_PASSWORD}

            DOCKER_IMAGE_NAME=${DOCKER_USERNAME}/zenobius

            docker build --cache-from=app -t ${DOCKER_IMAGE_NAME}:${CIRCLE_TAG} .
            echo "built image as ${DOCKER_IMAGE_NAME}:${CIRCLE_TAG}"
            echo "Docker image size $(docker image inspect ${DOCKER_IMAGE_NAME}:${CIRCLE_TAG} --format='{{.Size}}')"

            echo "tagging image as ${DOCKER_IMAGE_NAME}:latest"
            docker tag ${IMAGE_NAME}:${CIRCLE_TAG} ${DOCKER_IMAGE_NAME}:latest

            docker push ${IMAGE_NAME}:${CIRCLE_TAG}
            docker push ${IMAGE_NAME}:latest

      - run:
          name: Save Docker image layer cache
          when: on_success
          command: |
            mkdir -p /caches
            docker save -o ./docker-image.tar ${DOCKER_USERNAME}/zenobius:latest
            cp docker-image.tar /caches/

      - save_cache:
          when: on_success
          key: image-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - /caches/docker-image.tar

  build_website:
    working_directory: /build
    docker: {image: "docker:17.05.0-ce-git" }
    steps:
      - run:
          name: Build website
          command: |
            docker login --username=${DOCKER_USERNAME} --password=${DOCKER_PASSWORD}
            npm run generate
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory.
          # This is a directory on the container which is
	        # taken to be the root directory of the workspace.
          root: .
          paths:
            - docs/**/*

  deploy_website:
    working_directory: /build
    docker: {image: "docker:17.05.0-ce-git" }
    steps:
      - run: echo true

  test_website:
    working_directory: /build
    docker: {image: "docker:17.05.0-ce-git" }
    steps:
      - run: echo true

workflows:
  version: "2"
  # only builds new docker images
  # for tagged commites on
  # branches starting with 'docker'.
  build-docker-image:
    jobs:
      - build_image:
          filters:
            tags: { only: /^v.*/ }
            branch: { only: /^docker/ }

  build-deploy-website:
    jobs:
      # builds website on any branch or tag
      - build_website:
          filters:
            tags: { only: /.*/ }
      # runs tests on any branch or tag
      - test_website:
          requires:
            - build_website
          filters:
            tags: { only: /.*/ }
            branches: { ignore: /^docker/ }
      # deploys website only
      # for v tagged commits
      # on the master branch
      - deploy_website:
          requires:
            - test_website
          filters:
            tags: { only: /^v.*/ }
            branches: { only: /master/ }
