version: 2

jobs:

  build_image:
    working_directory: /build
    docker:
      - image: node:alpine
    steps:

      - checkout

      - run:
          name: install docker-compose
          command: |
            apk add --update --no-cache \
              py2-pip=9.0.1-r1 \
              docker \
              git \
              jq

            pip install \
              docker-compose==1.12.0

      - setup_remote_docker

      - run:
          name: deploy hashed image
          command: |
            DOCKER_IMAGE_NAME=${DOCKER_USERNAME}/zenobius
            DOCKER_IMAGE_NAME_REF=${DOCKER_IMAGE_NAME}:${CIRCLE_SHA1}

            docker login --username=${DOCKER_USERNAME} --password=${DOCKER_PASSWORD}
            docker build \
              --cache-from=app \
              --label="project.git.described=$(git describe --tags)" \
              --label="project.git.commit=${CIRCLE_SHA1}" \
              --label="project.ci.workflow=${CIRCLE_WORKFLOW_ID}" \
              --label="project.ci.job=${CIRCLE_JOB}" \
              --label="project.ci.buildNo=${CIRCLE_BUILD_NUM}" \
              --label="project.ci.buildurl=${CIRCLE_BUILD_URL}" \
              --label="project.ci.prs=${CIRCLE_PULL_REQUESTS}" \
              -t ${DOCKER_IMAGE_NAME_REF} .

            echo "Docker image size $(docker image inspect ${DOCKER_IMAGE_NAME_REF} --format='{{.Size}}')"
            docker push ${DOCKER_IMAGE_NAME_REF}

  test_image:
    working_directory: /build
    docker:
      - image: node:alpine
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: provision
          command: |
            apk add --update --no-cache \
              py2-pip=9.0.1-r1 \
              docker \
              git \
              jq

            pip install \
              docker-compose==1.12.0
      - run:
          name: Test docker image
          when: on_success
          command: |
            docker login --username=${DOCKER_USERNAME} --password=${DOCKER_PASSWORD}
            npm run ci:generate


  deploy_image:
    working_directory: /build
    docker:
      - image: node:alpine
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: provision
          command: |
            apk add --update --no-cache \
              py2-pip=9.0.1-r1 \
              docker \
              git \
              jq

            pip install \
              docker-compose==1.12.0
      - run:
          name: Deploy docker image
          when: on_success
          command: |
            docker login --username=${DOCKER_USERNAME} --password=${DOCKER_PASSWORD}
            TAG=$(git describe --tags HEAD | sed 's/\v//g')
            DOCKER_IMAGE_NAME=${DOCKER_USERNAME}/zenobius

            echo "tagging image as ${DOCKER_IMAGE_NAME}:${TAG}"
            docker tag DOCKER_IMAGE_NAME:${CIRCLE_SHA1} ${DOCKER_IMAGE_NAME}:${TAG}
            docker push ${DOCKER_IMAGE_NAME}:${TAG}

            echo "tagging image as ${DOCKER_IMAGE_NAME}:latest"
            docker tag DOCKER_IMAGE_NAME:${CIRCLE_SHA1} ${DOCKER_IMAGE_NAME}:latest
            docker push ${DOCKER_IMAGE_NAME}:latest


  build_website:
    working_directory: /build
    docker:
      - image: node:alpine
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: install docker-compose
          command: |
            apk add --update --no-cache \
              py2-pip=9.0.1-r1 \
              docker \
              git \
              jq

            pip install \
              docker-compose==1.12.0

      - run:
          name: docker login
          command: |
            docker login --username=${DOCKER_USERNAME} --password=${DOCKER_PASSWORD}

      - run:
          name: Build website
          command: |
              npm run generate

      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory.
          # This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: .
          paths:
            - docs/**/*

  deploy_website:
    working_directory: /build
    docker:
      - image: node:alpine
    steps:
      - checkout
      - setup_remote_docker
      - run: echo true

  test_website:
    working_directory: /build
    docker:
      - image: node:alpine
    steps:
      - checkout
      - setup_remote_docker
      - run: echo true

workflows:
  version: 2
  # only builds new docker images
  # - for tagged commites on
  # - branches starting with 'docker'.
  build-docker-image:
    jobs:
      - build_image:
          filters:
            tags: { only: /.*/ }
            branches: { only: /^docker/ }
      - test_image:
          requires:
            - build_image
          filters:
            tags: { only: /.*/ }
            branches: { only: /^docker/ }
      - deploy_image:
          requires:
            - test_image
          filters:
            tags: { only: /.*/ }
            branches: { only: /^docker/ }

  build-deploy-website:
    jobs:
      # builds website on:
      # - any branch (expcept those starting with docker)
      # - any tag
      - build_website:
          filters:
            tags: { only: /.*/ }
            branches: { ignore: /^docker/ }
      # runs tests on:
      # - any branch
      # - any tag
      - test_website:
          requires:
            - build_website
          filters:
            tags: { only: /.*/ }
            branches: { ignore: /^docker/ }
      # deploys website only
      # - for v tagged commits
      # - on the master branch
      - deploy_website:
          requires:
            - test_website
          filters:
            tags: { only: /^v.*/ }
            branches: { only: /master/ }
