version: "2.0"

services:

  frontend:
    image: ${repo}/frontend:${version}
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - DEBUG=project*,config*
    volumes:
      - ./frontend:/app
      - /app/node_modules/
