name: PR Checks

on:
  pull_request:

env:
  CI_SETTINGS__APP_DOCKER_REPO: docker.pkg.github.com/airtonix/zenobi.us

jobs:

  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Taskfile
        uses: Arduino/actions/setup-taskfile@master
        with:
          version: '3.0.0'

      - name: Build Docker Assets
        run: >-
          task setup
          REPO=$CI_SETTINGS__APP_DOCKER_REPO/site
          VERSION=$GITHUB_SHA

      - name: Build Site
        run: >-
          task frontend.build
          STAGE=ci
          SITE_DOMAIN=airtonix.github.io
          SITE_ROOT=zenobi.us
          SITE_PATH=pr/$GITHUB_SHA

      - name: Deploy Branch Preview
        run: >-
          task frontend.deploy
          DEPLOY_SOURCE=pr/$GITHUB_SHA
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: |
            Branch Preview Deployed:
              [https://airtonix.github.io/zenobi.us/pr/$GITHUB_SHA/](https://airtonix.github.io/zenobi.us/pr/$GITHUB_SHA/)

      - name: Run linting
        run: >-
          task app.lint

      - name: Run tests
        run: >-
          task app.test
